import { Civilization, UnitLine, Structure } from './types';

export const civilizationsData: Civilization[] = [
  {
    id: 'aztecs',
    name: 'Aztecas',
    style: 'Civilización de infantería y monjes',
    bonuses: [
      'Los aldeanos cargan +3 recursos extra.',
      'Las unidades militares se crean un 11% más rápido.',
      'Los monjes ganan 5 PS por cada tecnología de monasterio investigada.',
      'Empiezan con +50 de oro.',
    ],
    teamBonus: 'Las reliquias generan +33% de oro.',
    uniqueUnit: 'Guerrero Jaguar',
    uniqueTechs: {
      castle: 'Atlatl (+1 ataque y +1 alcance para los guerrilleros).',
      imperial: 'Guerras Florales (la infantería gana +4 de ataque).',
    },
  },
  {
    id: 'britons',
    name: 'Británicos',
    style: 'Civilización de arqueros',
    bonuses: [
      'Los centros urbanos cuestan -50% de madera a partir de la Edad de los Castillos.',
      'Los arqueros a pie (excepto los guerrilleros) tienen +1 de alcance en la Edad de los Castillos y +1 en la Imperial (para un total de +2).',
      'Los pastores trabajan un 25% más rápido.',
    ],
    teamBonus: 'Galerías de tiro con arco trabajan un 20% más rápido.',
    uniqueUnit: 'Arquero de Tiro Largo',
    uniqueTechs: {
      castle: 'Yeomen (+1 alcance para arqueros a pie, +2 ataque para torres).',
      imperial: 'Warwolf (los fundíbulos hacen daño de área).',
    },
  },
    {
    id: 'byzantines',
    name: 'Bizantinos',
    style: 'Civilización de defensa',
    bonuses: [
      'Los edificios tienen +10% de PS en la Alta Edad Media, +20% en la Feudal, +30% en los Castillos y +40% en la Imperial.',
      'Camellos, guerrilleros y piqueros cuestan -25%.',
      'Los Brulotes atacan un 25% más rápido.',
      'Avanzar a la Edad Imperial cuesta -33%.',
    ],
    teamBonus: 'Los monjes curan un 50% más rápido.',
    uniqueUnit: 'Catafracta',
    uniqueTechs: {
      castle: 'Fuego Griego (+1 alcance para los brulotes).',
      imperial: 'Logística (las catafractas tienen daño de área de arrollamiento).',
    },
  },
  {
    id: 'chinese',
    name: 'Chinos',
    style: 'Civilización flexible',
    bonuses: [
        'Comienzan con 3 aldeanos adicionales, pero -50 de madera y -200 de comida.',
        'Las tecnologías cuestan -10% en la Edad Feudal, -15% en los Castillos y -20% en la Imperial.',
        'Los centros urbanos soportan 10 de población y tienen +5 de línea de visión.',
        'Las galeras de demolición tienen +50% de PS.',
    ],
    teamBonus: 'Las granjas tienen +45 de comida.',
    uniqueUnit: 'Chu Ko Nu',
    uniqueTechs: {
        castle: 'Gran Muralla (+1000 PS para murallas y torres).',
        imperial: 'Cohetería (+2 de ataque para Chu Ko Nu, +4 para escorpiones).',
    },
  },
  {
    id: 'franks',
    name: 'Francos',
    style: 'Civilización de caballería',
    bonuses: [
      'Los castillos cuestan -25%.',
      'La caballería tiene +20% de PS.',
      'Las mejoras de granjas son gratis.',
      'Los recolectores de bayas trabajan un 15% más rápido.',
    ],
    teamBonus: 'Los caballeros tienen +2 de línea de visión.',
    uniqueUnit: 'Lanzador de Hachas',
    uniqueTechs: {
      castle: 'Tecnología de barbicada (los castillos tienen +20% de PS).',
      imperial: 'Hachas arrojadizas (+1 de alcance para los lanzadores de hachas).',
    },
  },
  {
    id: 'goths',
    name: 'Godos',
    style: 'Civilización de infantería',
    bonuses: [
        'La infantería cuesta -25% en Feudal, -30% en Castillos, -35% en Imperial.',
        'La infantería tiene +1 de ataque contra edificios.',
        'Los cazadores cargan +15 de carne y trabajan un 50% más rápido.',
        '+10 al límite de población en la Edad Imperial.',
    ],
    teamBonus: 'Los cuarteles trabajan un 20% más rápido.',
    uniqueUnit: 'Huscarle',
    uniqueTechs: {
        castle: 'Anarquía (crea huscarles en el cuartel).',
        imperial: 'Perfusión (los cuarteles crean unidades un 50% más rápido).',
    },
  },
   {
    id: 'huns',
    name: 'Hunos',
    style: 'Civilización de caballería y arqueros a caballo',
    bonuses: [
      'No necesitan casas, pero empiezan con -100 de madera.',
      'Los arqueros a caballo cuestan -10% en Castillos y -20% en Imperial.',
      'Los fundíbulos tienen +30% de precisión.',
    ],
    teamBonus: 'Los establos trabajan un 20% más rápido.',
    uniqueUnit: 'Tarkan',
    uniqueTechs: {
      castle: 'Ateísmo (+100 años de victoria en Reliquia/Maravilla, espionaje cuesta -50%).',
      imperial: 'Mercenarios (los tarkanes se pueden crear en los establos).',
    },
  },
    {
    id: 'italians',
    name: 'Italianos',
    style: 'Civilización naval y de arqueros',
    bonuses: [
      'Avanzar a la siguiente edad cuesta -15%.',
      'Las tecnologías del muelle cuestan -50%.',
      'Las unidades de pólvora cuestan -20%.',
      'Los barcos de pesca cuestan -15%.',
    ],
    teamBonus: 'Los condotieros están disponibles en el cuartel.',
    uniqueUnit: 'Ballestero Genovés, Condotiero',
    uniqueTechs: {
      castle: 'Escudos de Pavés (+1 armadura cuerpo a cuerpo y +1 anti-proyectil para unidades a pie).',
      imperial: 'Ruta de la Seda (las unidades comerciales cuestan -50%).',
    },
  },
   {
    id: 'khmer',
    name: 'Jemeres',
    style: 'Civilización de asedio y elefantes',
    bonuses: [
        'No se requieren edificios para avanzar de edad.',
        'Los elefantes de combate se mueven un 10% más rápido.',
        'Los aldeanos pueden guarecerse en las casas.',
    ],
    teamBonus: 'Los escorpiones tienen +1 de alcance.',
    uniqueUnit: 'Elefante Ballesta',
    uniqueTechs: {
        castle: 'Grúas (construye edificios un 20% más rápido).',
        imperial: 'Doble Ballesta (los elefantes ballesta y los escorpiones disparan dos proyectiles).',
    },
  },
   {
    id: 'lithuanians',
    name: 'Lituanos',
    style: 'Civilización de caballería y monjes',
    bonuses: [
      'Empiezan con +150 de comida.',
      'Lanceros y guerrilleros se mueven un 10% más rápido.',
      'Cada reliquia guarnecida otorga +1 de ataque a caballeros y leitis (máximo +4).',
    ],
    teamBonus: 'Los centros urbanos trabajan un 10% más rápido.',
    uniqueUnit: 'Leitis',
    uniqueTechs: {
      castle: 'Escudos de Colina (unidades de la línea de arquero y lancero ganan +2 de armadura anti-proyectil).',
      imperial: 'Tribuna de la Torre (los castillos disparan proyectiles adicionales).',
    },
  },
  {
    id: 'mayans',
    name: 'Mayas',
    style: 'Civilización de arqueros y águilas',
    bonuses: [
      'Empiezan con +1 aldeano, pero -50 de comida.',
      'Los recursos duran un 15% más.',
      'Los arqueros cuestan -10% en Feudal, -20% en Castillos, -30% en Imperial.',
    ],
    teamBonus: 'Las murallas cuestan -50%.',
    uniqueUnit: 'Arquero de Plumas',
    uniqueTechs: {
      castle: 'Obsidiana (los guerreros águila devuelven el daño recibido).',
      imperial: 'El Dorado (los guerreros águila tienen +40 PS).',
    },
  },
  {
    id: 'portuguese',
    name: 'Portugueses',
    style: 'Civilización naval y de pólvora',
    bonuses: [
      'Todas las unidades cuestan -20% de oro.',
      'Todas las naves tienen +10% de PS.',
      'La carraca puede construir feitorias en la Edad Imperial.',
    ],
    teamBonus: 'Línea de visión compartida desde el inicio del juego.',
    uniqueUnit: 'Carabela, Organ Gun',
    uniqueBuilding: 'Feitoria (genera recursos sin necesidad de aldeanos)',
    uniqueTechs: {
      castle: 'Carraca (las naves tienen +1 de armadura).',
      imperial: 'Arcabuz (las unidades de pólvora se benefician de la balística).',
    },
  },
  {
    id: 'spanish',
    name: 'Españoles',
    style: 'Civilización de pólvora y monjes',
    bonuses: [
        'Los constructores trabajan un 30% más rápido.',
        'Las mejoras de la herrería no cuestan oro.',
        'Las unidades de pólvora atacan un 18% más rápido.',
    ],
    teamBonus: 'Las carretas de mercancías generan +25% de oro.',
    uniqueUnit: 'Conquistador, Misionero',
    uniqueTechs: {
        castle: 'Inquisición (los monjes convierten un 10% más rápido).',
        imperial: 'Supremacía (los aldeanos son mejores en combate).',
    },
  },
  {
    id: 'teutons',
    name: 'Teutones',
    style: 'Civilización de infantería y asedio',
    bonuses: [
        'Los monjes curan desde el doble de distancia.',
        'Las torres guarnecen el doble de unidades y disparan el doble de flechas.',
        'Las troneras y herbicidas son gratis.',
        'Las granjas cuestan -40%.',
    ],
    teamBonus: 'Las unidades resisten la conversión.',
    uniqueUnit: 'Caballero de la Orden Teutónica',
    uniqueTechs: {
        castle: 'Placas de Hierro (+4 de armadura cuerpo a cuerpo para unidades de asedio).',
        imperial: 'Crenelaciones (+3 de alcance para castillos; la infantería guarnecida dispara flechas).',
    },
  },
  {
    id: 'vikings',
    name: 'Vikingos',
    style: 'Civilización de infantería y naval',
    bonuses: [
        'Los barcos de guerra cuestan -15% en Feudal, -15% en Castillos, -20% en Imperial.',
        'La infantería tiene +10% de PS en Feudal, +15% en Castillos, +20% en Imperial.',
        'Carretilla y Carro de mano son gratis.',
    ],
    teamBonus: 'Los muelles cuestan -15%.',
    uniqueUnit: 'Berserker, Drakkar',
    uniqueTechs: {
        castle: 'Jefe tribal (+10 PS para los Berserkers).',
        imperial: 'Berserkergang (los Berserkers se regeneran más rápido).',
    },
  },
];

export const unitLinesData: UnitLine[] = [
  {
    id: 'militia-line',
    baseName: 'Milicia',
    evolutions: [
      {
        name: 'Milicia',
        age: 'Alta Edad Media',
        description: 'Infantería básica disponible en la Alta Edad Media. Débil pero barata.',
        stats: { hp: 40, attack: '4 (cuerpo a cuerpo)', range: 0, armor: '0/1', speed: 0.9 },
        maxStats: { hp: 40, attack: '4+4', range: 0, armor: '3/5', speed: 0.9 },
      },
      {
        name: 'Hombre de Armas',
        age: 'Edad Feudal',
        description: 'Mejora de la Milicia, más fuerte y resistente.',
        stats: { hp: 45, attack: '6 (cuerpo a cuerpo)', range: 0, armor: '0/1', speed: 0.9 },
        maxStats: { hp: 45, attack: '6+4', range: 0, armor: '3/5', speed: 0.9 },
      },
      {
        name: 'Espadachín de Mandoble',
        age: 'Edad de los Castillos',
        description: 'Infantería poderosa con un gran mandoble.',
        stats: { hp: 60, attack: '9 (cuerpo a cuerpo)', range: 0, armor: '1/2', speed: 0.9 },
        maxStats: { hp: 60, attack: '9+4', range: 0, armor: '4/6', speed: 0.9 },
      },
      {
        name: 'Campeón',
        age: 'Edad Imperial',
        description: 'La élite de la infantería, capaz de enfrentarse a casi cualquier unidad.',
        stats: { hp: 70, attack: '13 (cuerpo a cuerpo)', range: 0, armor: '1/2', speed: 0.9 },
        maxStats: { hp: 70, attack: '13+4', range: 0, armor: '4/6', speed: 0.9 },
      },
    ],
  },
  {
    id: 'spearman-line',
    baseName: 'Lancero',
    evolutions: [
      {
        name: 'Lancero',
        age: 'Edad Feudal',
        description: 'Infantería barata, efectiva contra caballería.',
        stats: { hp: 45, attack: '3 (cuerpo a cuerpo)', range: 0, armor: '0/0', speed: 1.0 },
      },
      {
        name: 'Piquero',
        age: 'Edad de los Castillos',
        description: 'Mejora del lancero, con mayor bonificación contra caballería.',
        stats: { hp: 55, attack: '4 (cuerpo a cuerpo)', range: 0, armor: '0/0', speed: 1.0 },
      },
      {
        name: 'Alabardero',
        age: 'Edad Imperial',
        description: 'La mejor infantería anti-caballería del juego.',
        stats: { hp: 60, attack: '6 (cuerpo a cuerpo)', range: 0, armor: '0/0', speed: 1.0 },
      },
    ],
  },
    {
    id: 'eagle-warrior-line',
    baseName: 'Guerrero Águila',
    evolutions: [
      {
        name: 'Guerrero Águila Explorador',
        age: 'Edad Feudal',
        description: 'Infantería rápida de las civilizaciones mesoamericanas. Reemplaza al explorador a caballo.',
        stats: { hp: 50, attack: '4 (cuerpo a cuerpo)', range: 0, armor: '0/2', speed: 1.1 },
      },
      {
        name: 'Guerrero Águila',
        age: 'Edad de los Castillos',
        description: 'Mejora del explorador. Rápido y fuerte contra arqueros y monjes.',
        stats: { hp: 55, attack: '7 (cuerpo a cuerpo)', range: 0, armor: '0/3', speed: 1.15 },
      },
      {
        name: 'Guerrero Águila de Élite',
        age: 'Edad Imperial',
        description: 'La forma final del guerrero águila, una unidad de incursión letal.',
        stats: { hp: 60, attack: '9 (cuerpo a cuerpo)', range: 0, armor: '0/4', speed: 1.2 },
      },
    ],
  },
  {
    id: 'archer-line',
    baseName: 'Arquero',
    evolutions: [
      {
        name: 'Arquero',
        age: 'Edad Feudal',
        description: 'Unidad de proyectil básica, efectiva contra infantería a distancia.',
        stats: { hp: 30, attack: '4 (proyectil)', range: 4, armor: '0/0', speed: 0.96 },
        maxStats: { hp: 30, attack: '4+5', range: 4, armor: '3/4', speed: 0.96 },
      },
      {
        name: 'Ballestero',
        age: 'Edad de los Castillos',
        description: 'Mejora del arquero con más daño y vida.',
        stats: { hp: 35, attack: '5 (proyectil)', range: 5, armor: '0/0', speed: 0.96 },
        maxStats: { hp: 35, attack: '5+5', range: 5, armor: '3/4', speed: 0.96 },
      },
      {
        name: 'Arbalestero',
        age: 'Edad Imperial',
        description: 'La forma final del arquero, con gran poder de ataque.',
        stats: { hp: 40, attack: '6 (proyectil)', range: 5, armor: '0/0', speed: 0.96 },
        maxStats: { hp: 40, attack: '6+5', range: 5, armor: '3/4', speed: 0.96 },
      },
    ],
  },
  {
    id: 'skirmisher-line',
    baseName: 'Guerrillero',
    evolutions: [
      {
        name: 'Guerrillero',
        age: 'Edad Feudal',
        description: 'Infantería con escudo anti-proyectiles. Efectiva contra arqueros.',
        stats: { hp: 30, attack: '2 (proyectil)', range: 4, armor: '0/3', speed: 0.96 },
      },
      {
        name: 'Guerrillero de Élite',
        age: 'Edad de los Castillos',
        description: 'Mejora del guerrillero con más ataque y armadura anti-proyectil.',
        stats: { hp: 35, attack: '3 (proyectil)', range: 5, armor: '0/4', speed: 0.96 },
      },
      {
        name: 'Guerrillero Imperial',
        age: 'Edad Imperial',
        description: 'Una mejora adicional disponible para algunas civilizaciones.',
        stats: { hp: 40, attack: '4 (proyectil)', range: 5, armor: '0/5', speed: 0.96 },
      },
    ],
  },
    {
    id: 'scout-cavalry-line',
    baseName: 'Jinete de Exploración',
    evolutions: [
      {
        name: 'Jinete de Exploración',
        age: 'Alta Edad Media',
        description: 'Caballería rápida para exploración y hostigamiento temprano.',
        stats: { hp: 45, attack: '3 (cuerpo a cuerpo)', range: 0, armor: '0/2', speed: 1.2 },
      },
      {
        name: 'Caballería Ligera',
        age: 'Edad de los Castillos',
        description: 'Mejora del jinete, más resistente y con ataque adicional contra monjes.',
        stats: { hp: 60, attack: '7 (cuerpo a cuerpo)', range: 0, armor: '0/2', speed: 1.35 },
      },
       {
        name: 'Húsar',
        age: 'Edad Imperial',
        description: 'Caballería ligera de élite, excelente para incursiones y matar unidades débiles.',
        stats: { hp: 75, attack: '7 (cuerpo a cuerpo)', range: 0, armor: '0/2', speed: 1.4 },
      },
    ],
  },
  {
    id: 'knight-line',
    baseName: 'Caballero',
    evolutions: [
       {
        name: 'Caballero',
        age: 'Edad de los Castillos',
        description: 'Caballería pesada, el núcleo de muchos ejércitos.',
        stats: { hp: 100, attack: '10 (cuerpo a cuerpo)', range: 0, armor: '2/2', speed: 1.35 },
      },
      {
        name: 'Cavalier',
        age: 'Edad Imperial',
        description: 'Mejora del caballero, una unidad de élite temible.',
        stats: { hp: 120, attack: '12 (cuerpo a cuerpo)', range: 0, armor: '2/2', speed: 1.35 },
      },
       {
        name: 'Paladín',
        age: 'Edad Imperial',
        description: 'La unidad de caballería más poderosa del juego.',
        stats: { hp: 160, attack: '14 (cuerpo a cuerpo)', range: 0, armor: '2/3', speed: 1.35 },
      },
    ],
  },
    {
    id: 'camel-rider-line',
    baseName: 'Jinete de Camello',
    evolutions: [
       {
        name: 'Jinete de Camello',
        age: 'Edad de los Castillos',
        description: 'Caballería efectiva contra otra caballería.',
        stats: { hp: 100, attack: '6 (cuerpo a cuerpo)', range: 0, armor: '0/0', speed: 1.45 },
      },
      {
        name: 'Jinete de Camello Pesado',
        age: 'Edad Imperial',
        description: 'Mejora del jinete de camello, muy fuerte contra caballería.',
        stats: { hp: 120, attack: '7 (cuerpo a cuerpo)', range: 0, armor: '0/0', speed: 1.45 },
      },
       {
        name: 'Jinete de Camello Imperial',
        age: 'Edad Imperial',
        description: 'La unidad anti-caballería montada definitiva.',
        stats: { hp: 140, attack: '9 (cuerpo a cuerpo)', range: 0, armor: '0/0', speed: 1.45 },
      },
    ],
  },
  {
    id: 'battle-elephant-line',
    baseName: 'Elefante de Combate',
    evolutions: [
       {
        name: 'Elefante de Combate',
        age: 'Edad de los Castillos',
        description: 'Caballería lenta pero increíblemente poderosa con daño de área.',
        stats: { hp: 250, attack: '12 (cuerpo a cuerpo)', range: 0, armor: '1/2', speed: 0.85 },
      },
      {
        name: 'Elefante de Combate de Élite',
        age: 'Edad Imperial',
        description: 'Una versión aún más fuerte y resistente del Elefante de Combate.',
        stats: { hp: 300, attack: '16 (cuerpo a cuerpo)', range: 0, armor: '1/3', speed: 0.85 },
      },
    ],
  },
    {
    id: 'steppe-lancer-line',
    baseName: 'Lancero de la Estepa',
    evolutions: [
       {
        name: 'Lancero de la Estepa',
        age: 'Edad de los Castillos',
        description: 'Caballería con +1 de alcance que puede atacar sobre unidades.',
        stats: { hp: 60, attack: '8 (cuerpo a cuerpo)', range: 1, armor: '0/1', speed: 1.45 },
      },
      {
        name: 'Lancero de la Estepa de Élite',
        age: 'Edad Imperial',
        description: 'Versión mejorada con más vida y ataque.',
        stats: { hp: 80, attack: '10 (cuerpo a cuerpo)', range: 1, armor: '0/2', speed: 1.45 },
      },
    ],
  },
];

export const structuresData: Structure[] = [
    {
        id: 'town-center',
        name: 'Centro Urbano',
        image: 'https://picsum.photos/seed/towncenter/400/250',
        hp: 2400,
        armor: '5/5',
        function: 'Edificio principal. Crea aldeanos y permite avanzar de edad. Sirve como punto de entrega de recursos.',
        creates: ['Aldeano'],
        researches: ['Telar', 'Guardia urbana', 'Edad Feudal', 'Edad de los Castillos', 'Edad Imperial', 'Carretilla', 'Carro de mano'],
    },
    {
        id: 'house',
        name: 'Casa',
        image: 'https://picsum.photos/seed/house/400/250',
        hp: 550,
        armor: '0/7',
        function: 'Aumenta el límite de población en 5.',
    },
    {
        id: 'barracks',
        name: 'Cuartel',
        image: 'https://picsum.photos/seed/barracks/400/250',
        hp: 1200,
        armor: '3/3',
        function: 'Entrena unidades de infantería y pesquisa sus tecnologías.',
        creates: ['Milicia', 'Lancero', 'Guerrero Águila'],
        researches: ['Hombre de Armas', 'Piquero', 'Alabardero', 'Campeón', 'Suministros', 'Brandales', 'Guerrero Águila de Élite'],
    },
     {
        id: 'dock',
        name: 'Muelle',
        image: 'https://picsum.photos/seed/dock/400/250',
        hp: 1800,
        armor: '3/3',
        function: 'Entrena unidades navales y las mejora. También sirve como punto de entrega para barcos de pesca.',
        creates: ['Barco de Pesca', 'Galera', 'Brulote', 'Barco de Demolición', 'Carreta de Mercancías', 'Drakkar', 'Carabela'],
        researches: ['Branquias', 'Galera de Guerra', 'Galeón', 'Fundíbulos de Élite', 'Barco de Demolición Pesado', 'Astillero'],
    },
    {
        id: 'mill',
        name: 'Molino',
        image: 'https://picsum.photos/seed/mill/400/250',
        hp: 600,
        armor: '0/7',
        function: 'Punto de entrega para granjas, recolectores de bayas y cazadores. Investiga mejoras para granjas.',
        researches: ['Collera', 'Arado Pesado', 'Rotación de Cultivos'],
    },
     {
        id: 'lumber-camp',
        name: 'Campamento Maderero',
        image: 'https://picsum.photos/seed/lumber/400/250',
        hp: 600,
        armor: '0/7',
        function: 'Punto de entrega para leñadores. Investiga mejoras para la recolección de madera.',
        researches: ['Hacha de Doble Filo', 'Sierras de Arco', 'Sierra de Dos Hombres'],
    },
     {
        id: 'mining-camp',
        name: 'Campamento Minero',
        image: 'https://picsum.photos/seed/mining/400/250',
        hp: 600,
        armor: '0/7',
        function: 'Punto de entrega para mineros. Investiga mejoras para la recolección de oro y piedra.',
        researches: ['Minería Aurífera', 'Minería de Piedra', 'Torno de Oro', 'Torno de Piedra'],
    },
    {
        id: 'walls',
        name: 'Murallas y Puertas',
        image: 'https://picsum.photos/seed/walls/400/250',
        hp: 750,
        armor: '2/2',
        function: 'Estructuras defensivas para proteger tu base. Se pueden mejorar a Muros de Piedra y Muros Fortificados.',
        upgradesTo: 'Muro de Piedra -> Muro Fortificado',
    },
     {
        id: 'archery-range',
        name: 'Galería de Tiro con Arco',
        image: 'https://picsum.photos/seed/archery/400/250',
        hp: 1200,
        armor: '3/3',
        function: 'Entrena unidades de arquero.',
        creates: ['Arquero', 'Guerrillero', 'Arquero a Caballo'],
        researches: ['Ballestero', 'Arbalestero', 'Guerrillero de Élite', 'Arquero a Caballo Pesado', 'Tácticas de los Partos', 'Reposa-pulgares'],
    },
     {
        id: 'stable',
        name: 'Establo',
        image: 'https://picsum.photos/seed/stable/400/250',
        hp: 1500,
        armor: '3/3',
        function: 'Entrena unidades de caballería.',
        creates: ['Jinete de Exploración', 'Caballero', 'Jinete de Camello', 'Lancero de la Estepa', 'Elefante de Combate'],
        researches: ['Caballería Ligera', 'Húsar', 'Cavalier', 'Paladín', 'Camello Pesado', 'Líneas de Sangre', 'Ganadería'],
    },
     {
        id: 'blacksmith',
        name: 'Herrería',
        image: 'https://picsum.photos/seed/blacksmith/400/250',
        hp: 2100,
        armor: '3/3',
        function: 'Investiga mejoras de ataque y armadura para unidades militares.',
        researches: ['Forja', 'Fundición', 'Alto Horno', 'Armadura de levas', 'Cota de malla', 'Armadura de placas', 'Flechas de punta de aguja', 'Fabricante de flechas', 'Bratsera'],
    },
    {
        id: 'market',
        name: 'Mercado',
        image: 'https://picsum.photos/seed/market/400/250',
        hp: 2100,
        armor: '3/3',
        function: 'Permite comerciar recursos, crear carretas de mercancías e investigar mejoras económicas.',
        creates: ['Carreta de Mercancías'],
        researches: ['Acuñación', 'Banca', 'Gremios', 'Carro de Mercancías', 'Caravana'],
    },
     {
        id: 'monastery',
        name: 'Monasterio',
        image: 'https://picsum.photos/seed/monastery/400/250',
        hp: 1200,
        armor: '3/3',
        function: 'Crea monjes y investiga tecnologías religiosas y de curación.',
        creates: ['Monje'],
        researches: ['Redención', 'Expiación', 'Herejía', 'Fervor', 'Santidad', 'Teocracia', 'Iluminación', 'La Imprenta', 'Fé'],
    },
     {
        id: 'university',
        name: 'Universidad',
        image: 'https://picsum.photos/seed/university/400/250',
        hp: 2100,
        armor: '3/3',
        function: 'Investiga una amplia gama de tecnologías avanzadas para edificios y unidades.',
        researches: ['Albañilería', 'Arquitectura', 'Grúa de Rueda de Izar', 'Disparo calentado', 'Torre de Guardia', 'Fortaleza', 'Fortaleza Reforzada', 'Balística', 'Química', 'Ingenieros de Asedio'],
    },
    {
        id: 'watch-tower',
        name: 'Torre de Guardia',
        image: 'https://picsum.photos/seed/watchtower/400/250',
        hp: 1020,
        armor: '1/5',
        function: 'Estructura defensiva que dispara flechas a los enemigos cercanos.',
        upgradesTo: 'Fortaleza -> Fortaleza Reforzada -> Torre del Homenaje',
    },
    {
        id: 'castle',
        name: 'Castillo',
        image: 'https://picsum.photos/seed/castle/400/250',
        hp: 4800,
        armor: '8/8',
        function: 'Poderosa fortaleza defensiva. Crea unidades únicas y fundíbulos. Investiga tecnologías únicas.',
        creates: ['Unidad Única', 'Fundíbulo'],
        researches: ['Tecnología Única (Castillos)', 'Tecnología Única (Imperial)', 'Espionaje/Traición', 'Hoardings', 'Reclutamiento'],
    }
];